# Build Workflow

name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.editorconfig'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'SECURITY.md'
      - 'LICENSE'
      - '.gitattributes'
      - '.gitignore'
      - 'format/**'

concurrency:
  group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    name: Build

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: |
            8
            16
            17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary-as-pr-comment: always
          validate-wrappers: true
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/v1' }}

      - uses: actions/cache@v4
        with:
          path: |
            **/loom-cache
            **/prebundled-jars
          key: ${{ runner.os }}-loom-v1-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-loom-v1

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: oneconfig-artifacts
          path: versions/**/build/libs/
